import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Home from '../app/Home/page'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav className="flex flex-row justify-evenly">
            <ul className="flex space-x-10 mt-2">
              <li>Product</li>
              <li>Solution</li>
              <li>Resources</li>
              <li>pricing</li>
            </ul>
            <ul className="flex items-center space-x-10">
              <li>Log in</li>
              <li>contact</li>
              <li className="bg-blue-700 p-2 rounded-sm">Get started-Free</li>
            </ul>
          </nav>
        </div>
        <Home/>
        {children}
      </body>
    </html>
  );
}
