import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Home from './Home/intro/page';
import Progressbar from '../components/ProgressBar';
import Sessionwrap from '../app/camponent/sessionwraper';
import Link from "next/link";
import Nav from './nav/page'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} > 
        <Nav/>
        <Progressbar/>
        <Home/>
        </body>
      
    </html>
  );
}
